services:
  redis:
    image: redis:6.2-alpine
    container_name: redis-dev
    ports:
      - '6379:6379'
    networks:
      - temp

  back:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: server-dev
    restart: always
    ports:
      - 8000:8000
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_DATASOURCE_URL: >
        jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
        ?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"

      # Redis
      SPRING_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: "6379"

      # AWS 자격증명 (표준명)
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"

      # S3Config 에 바인딩할 리전
      SPRING_CLOUD_AWS_REGION_STATIC: "${AWS_REGION}"

      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - redis
    networks:
      - temp

networks:
  temp:
    driver: bridge
