# src/main/resources/application-dev.yml
spring:
  config:
    activate:
      on-profile: dev

  cloud:
    aws:
      s3:
        bucket: moru-image-bucket-810761468597

  # Redis 설정
  redis:
    host: redis
    port: 6379

  lettuce:
    shutdown-timeout: 100ms
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0

  # <<< 여기 아래로 들여쓰기
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration