server:
  port: 8000

spring:
  # =====================================================
  # 여기에 추가하시면 됩니다.
  # 'dev' 프로필을 활성화하여 DummyDataInitializer가 실행되도록 합니다.
  profiles:
    active: dev

  # (선택사항이지만 권장) data.sql 파일이 자동으로 실행되는 것을 방지합니다.
  sql:
    init:
      mode: never
  devtools:
    restart:
      enabled: false # 이 설정을 추가하여 자동 재시작을 비활성화합니다.
  # =====================================================
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/moru_db
    username: root
    password: spring12!    # 비밀번호 없으면 이대로 둬도 됨
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: $2a$10$SUKPX4PRaPeNnPjG8r7oJOoPrDGFw4SwQTk/sGz.js2NkaljfIkAi
  jpa:
    hibernate:
      ddl-auto: update   # 개발 중에는 update / 운영 시에는 validate 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: moru-image-bucket
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

jwt:
  secret: w9X37H8oCdKf4Blh5Mv2N5QwU9YeT4F2t4WJ0jB9FpE

