server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moru_db
    username: root
    password: spring12!     # 비밀번호 없으면 이대로 둬도 됨
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: 1111

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중에는 update / 운영 시에는 validate 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
