server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local

  redis:
    host: localhost
    port: 6379

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: moru-image-bucket-810761468597