name: moru-server-deploy

on:
  push:
    branches:
      - develop  # moru는 develop 브랜치 기준으로 배포하도록 설정

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy moru Server (prod)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ~/KUIT_MORU_Server
            git checkout develop
            kill -9 $(lsof -t -i :8000)
            git add .
            git commit -m "temp commit"
            git fetch origin develop
            git merge origin/develop
            if [ $? -ne 0 ]; then
              echo "Merge conflict detected. Resolving by applying remote changes."
              git checkout --theirs $(git diff --name-only --diff-filter=U)
              git add .
              git commit -m "Resolved merge conflicts by applying remote changes."
            else
              echo "Merge successful, no conflicts detected."
            fi

./gradlew clean build
docker rm -f server-dev --force
docker rmi server-dev
docker compose -f docker-compose-dev.yml -p server-dev up --build -d
